### ISSUE TITLE
yarn dev: Internal server error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by borisboguslavsky** [hyperbrew/vite-cep-plugin#8]
Running `yarn dev` for me results in this error message:

```
4:16:45 PM [vite] Internal server error: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at transformIndexHtml (C:\Users\Boris\Dropbox\replicator\node_modules\vite-cep-plugin\lib\index.js:117:20)
      at applyHtmlTransforms (C:\Users\Boris\Dropbox\replicator\node_modules\vite\dist\node\chunks\dep-971d9e33.js:21713:27)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async viteIndexHtmlMiddleware (C:\Users\Boris\Dropbox\replicator\node_modules\vite\dist\node\chunks\dep-971d9e33.js:53300:28)
```

Commenting out the following code inside of index.js (line 117) works around this issue:

```
Object.keys(opts.bundle).filter(function (file) {
  if (file.includes("css")) {
    var newCode_1 = opts.bundle[file].source
      .replace(/\(\.\/assets/g, "(../assets")
      .replace(/\(\/assets/g, "(./");
    opts.bundle[file].source = newCode_1;
  }
});
```

**Comment by justintaylor-dev** [comment]
Fixed in 0.1.6
